
## spring cloud access&secret config
## 可以访问如下地址查看: https://usercenter.console.aliyun.com/#/manage/ak
#alibaba.cloud.access-key=****
#alibaba.cloud.secret-key=****
    ## 服务名
spring:
  application:
    name: @artifactId@
    ## 应用服务web访问端口
server:
  port: 8080
  ## ActuatorWeb访问端口
management:
  server:
    port: 8081
  endpoints:
    jmx:
      exposure:
        include: *
    web:
      exposure:
        exclude: *
  endpoint:
    health:
      show-details: always




